### ISSUE TITLE
Iterator/pagination fails on empty response

### ISSUE THREAD

**Issue by lowell80** [ctera/ctera-python-sdk#263]
I've run into this issue a few times when the SDK supports return multiple items but the actual API response ends up being empty.  The developer/end-user ends up with an unhelpful exception like `'NoneType' object has no attribute 'hasMore'` from the iteration code which hides the real issue.

I was able to prove this out with the scenarios I was hitting by explicitly checking for a blank response (None) in the BaseResponse constructor, but unfortunately this moves the exception a stack-steps closer to the source, it's still ends up being quite cryptic to debug.  (I was only able to definitely pinpoint my 'blank response' theory by passing all HTTPS traffic through mitmproxy and seeing the actual blank response payload). It seems like the correct behavior would be to return a no-op iterable  (like `iter([])`) when there's no data, but that didn't seem to be happening in my use case.

## Exception in the wild
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/gqal/CTERA/venv39/lib64/python3.9/site-packages/cterasdk/lib/iterator.py", line 21, in __next__
    self._more, page = self.page()
  File "/home/gqal/CTERA/venv39/lib64/python3.9/site-packages/cterasdk/lib/iterator.py", line 51, in page
    return response.more, response.objects
  File "/home/gqal/CTERA/venv39/lib64/python3.9/site-packages/cterasdk/lib/iterator.py", line 74, in more
    return self._response.hasMore
AttributeError: 'NoneType' object has no attribute 'hasMore'
```

## Trapping None sooner
Note that depending on which Response class was used, there's a bunch of different failure scenarios here. DefaultResponse will complain about `hasMore` or `objects` and FetchResourcesResponse will complain about `items` and so on.  All of this stems from the fact that BaseResponse never checks if `response` is a valid or not.   So my thought was to fix this by checking for None in the base class (as shown below).

But. while the following code "works", and it's probably a good idea to check for None, but trapping the bug here was ultimately not very helpful from a troubleshooting perspective.  Therefore I think there may be a better fix.  (Hence no PR)

```diff
diff --git a/cterasdk/lib/iterator.py b/cterasdk/lib/iterator.py
index 06480f8..1b1ad10 100644
--- a/cterasdk/lib/iterator.py
+++ b/cterasdk/lib/iterator.py
@@ -54,6 +54,7 @@ class QueryIterator(BaseIterator):
 class BaseResponse:
 
     def __init__(self, response):
+        assert response is not None, "response cannot be None"
         self._response = response
 
     @property
```

**Comment by lowell80** [comment]
I'm hitting more of these null-response related issues. These seem to follow a loose pattern, but they can't always be easily reproduced.

```
Traceback (most recent call last):
  File "/opt/splunk/etc/apps/TA-CTERA-CloudStorageGateway/bin/ctera_filter.py", line 299, in stream_events
    self._stream_events(inputs, ew)
  File "/opt/splunk/etc/apps/TA-CTERA-CloudStorageGateway/bin/ctera_filter.py", line 427, in _stream_events
    for record in sdk.collect_av_servers():
  File "/opt/splunk/etc/apps/TA-CTERA-CloudStorageGateway/bin/ctera_filter.py", line 199, in collect_av_servers
    for av in self._admin.antivirus.list_servers(
  File "/opt/splunk/etc/apps/TA-CTERA-CloudStorageGateway/bin/../lib/cterasdk/lib/iterator.py", line 21, in __next__
    self._more, page = self.page()
  File "/opt/splunk/etc/apps/TA-CTERA-CloudStorageGateway/bin/../lib/cterasdk/lib/iterator.py", line 51, in page
    return response.more, response.objects
  File "/opt/splunk/etc/apps/TA-CTERA-CloudStorageGateway/bin/../lib/cterasdk/lib/iterator.py", line 74, in more
    return self._response.hasMore
AttributeError: 'NoneType' object has no attribute 'hasMore'
```

```
Traceback (most recent call last):
  File "/opt/splunk/etc/apps/TA-CTERA-CloudStorageGateway/bin/ctera_filter.py", line 142, in collect_all_filers
    yield self.collect_filer_status(filer)
  File "/opt/splunk/etc/apps/TA-CTERA-CloudStorageGateway/bin/ctera_filter.py", line 173, in collect_filer_status
    data["drives"] = [sdk_to_dict(i, **common) for i in filer.drive.get_status()]
TypeError: 'NoneType' object is not iterable
```

The data collection script that pulls various stats from the CTERA SDK runs every 60 seconds.  The first error from `antivirus.list_servers()` seems to be failing exactly once an hour at about 32-33 mins past the hour, which makes me think there's some kind of schedule operation that's impacting the system.

The second case, `filer.drive.get_status()` doesn't always return an iterable object.  I see this happening between 16-37 times an hour; so that means it's failing about 25-60% of the time. And when it does return, it doesn't always return the same length sequence.  There are 32 drives that should return, and normally all 32 are returned, but sometimes we see 16, or 6, or 31, ....

My use case doesn't require perfect results every time, because information is collected rather frequently.  I'm at a loss as to what's really going on or if this is expected behavior or not.  I suggest that the cterasdk should either (1) return and empty sequence if empty responses from the server are normal and acceptable, or (2) raise an explicit exception with additional information about what when wrong.

**Comment by saimonation** [comment]
From my testing this occurs when the client session expires. The NULL response occurs because the server redirects to the Portal app's login page. I’m working on a solution to raise an exception in this case, which will notify you (the client) to re-authenticate and retry.

**Comment by lowell80** [comment]
That scenario makes sense.  I know I hit this during my initial development, where I was doing some interactive testing to a timeout is a feasible explication.  But I think I hit it on fresh connections too, but it's been too long for me to say that with full confidence.

Any progress on your side?  I'm happy to test with a pre-release or branch when the time comes.

**Comment by saimonation** [comment]
Yes - I have a branch ready with the fix, but requires more testing to verify the logout scenarios when the authentication is federated to a 3rd party identity provider. I expect it will incorporated by early February. We had to prioritize work related to accessing previous versions

**Comment by saimonation** [comment]
@lowell80 , we have incorporated functionality to identify an expired session and raise an exception: `SessionExpired`. I'll close this issue for now unless you indicate you are able to reproduce it still
